### ISSUE TITLE
Compagnies should have some privacy at root level.

### ISSUE THREAD

**Issue by lerer00** [lerer00/latude-dev-portal#9]
The CompanyFactory.sol only fills an array on which we query afterward to retreive all compagnies created. This is too flat and not quite useful. We should do a mapping like so:

`mapping (address => address[]) companies;`

instead of 

`address[] public companies;`

This mapping will now have every compagnies owned by the user calling this contract.
```
function getCompanies() constant returns(address[]) {
     return companies[msg.sender];
}
```

**Comment by lerer00** [comment]
@vadimkerr What do you think?

**Comment by vadimkerr** [comment]
`function getCompanies() constant returns(address[]) {
     return companies[msg.sender];
}`
That's not the best solution here. If we do so then one address won't be able to create multiple companies.

**Comment by vadimkerr** [comment]
Don't really understand what do you mean by "privacy"

**Comment by lerer00** [comment]
You'r right, we want users to be able to create multiple companies. I'll work on that design. 

The term privacy here is because our current design return every company ever created within a list, and not only the one current user have access. This will cause the dashboard to be filled with companies that user don't even know.

**Comment by vadimkerr** [comment]
It can't have any privacy at all since all states are public on blockchain. You can just hide it in UI but it won't be "private" anyway, it will be just "not visible" from the website.

**Comment by lerer00** [comment]
Yes, I'm totally fine with "not visible", that's what I was trying to achieve. I only want companies that the user is the owner. Since you did the Ownable contract, all interactions are allowed only to the owner.
